name: animearc_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  animate_do: ^4.2.0
  chewie: ^1.11.3
  file_picker: ^8.1.7
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  supabase_flutter: ^2.8.3
  url_launcher: ^6.3.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/

